### ISSUE TITLE
Nicer error message when class is not registered

### ISSUE THREAD

**Issue by kaedroho** [wagtail/telepath-unpack#3]
When you try to unpack something which uses an unregistered class, you get the following error:

```
Uncaught TypeError: undefined is not a constructor
```

I think it would be helpful to include the missing class name in the error message

**Comment by Durgavasu58** [comment]
after uprading wagtail to 5.1 version iam getting error
![image](https://github.com/wagtail/telepath-unpack/assets/75153512/4b357c7e-dfc9-4d64-ad8a-6f5bbbec0cbb)
